service: tipping

provider:
  name: aws
  runtime: python3.8
  timeout: 900
  stage: prod
  region: ap-southeast-2
  environment:
    DATA_SCIENCE_SERVICE: ${env:DATA_SCIENCE_SERVICE}
    DATA_SCIENCE_SERVICE_TOKEN: ${env:DATA_SCIENCE_SERVICE_TOKEN}
    FAUNA_SCHEME: ${env:FAUNA_SCHEME, 'https'}
    FAUNA_SECRET: ${env:FAUNA_SECRET}
    FOOTY_TIPS_USERNAME: ${env:FOOTY_TIPS_USERNAME}
    FOOTY_TIPS_PASSWORD: ${env:FOOTY_TIPS_PASSWORD}
    MONASH_USERNAME: ${env:MONASH_USERNAME}
    MONASH_PASSWORD: ${env:MONASH_PASSWORD}
    PYTHON_ENV: ${env:PYTHON_ENV, 'production'}
    ROLLBAR_TOKEN: ${env:ROLLBAR_TOKEN}
    SPLASH_SERVICE: ${env:SPLASH_SERVICE}
    TIPPING_SERVICE_TOKEN: ${env:TIPPING_SERVICE_TOKEN}
    TIPRESIAS_APP: ${env:TIPRESIAS_APP}
    TIPRESIAS_APP_TOKEN: ${env:TIPRESIAS_APP_TOKEN}
plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-prune-plugin
custom:
  pythonRequirements:
    dockerizePip: false # We run sls inside Docker already
    slim: true
    fileName: requirements.prod.txt
  prune:
    automatic: true
    includeLayers: true
    number: 3

package:
  include:
    - handler.py
    - src/tipping/**
    - sqlalchemy-fauna/**
  exclude:
    - "**"

functions:
  update_fixture_data:
    handler: handler.update_fixture_data
    events:
      - schedule:
          # Monday-Tuesday, 12am UTC
          rate: cron(0 0 ? * 2-3 *)
          enabled: true
  update_match_predictions:
    handler: handler.update_match_predictions
    events:
      - schedule:
          # Everyday, 12am UTC
          rate: cron(0 0 ? * 1-7 *)
          enabled: true
          input:
            ml_model_names: tipresias_margin_2021,tipresias_proba_2021
      - schedule:
          # Everyday, 1am UTC
          rate: cron(0 1 ? * 1-7 *)
          enabled: true
          input:
            ml_model_names: tipresias_margin_2020,tipresias_proba_2020
  update_matches:
    handler: handler.update_matches
    events:
      - schedule:
          # Wednesday, 12am UTC
          rate: cron(0 0 ? * 4 *)
          enabled: true
  update_match_results:
    handler: handler.update_match_results
    events:
      - schedule:
          # Thurs-Sun, 2am-2pm UTC (next day, 12pm/1pm-12am/1am Melbourne time, depending on DST)
          rate: cron(0 2-14/3 ? * 1,5-7 *)
          enabled: true
  fetch_match_predictions:
    handler: handler.fetch_match_predictions
    timeout: 30
    events:
      - http:
          path: predictions
          method: get
  fetch_match_results:
    handler: handler.fetch_match_results
    timeout: 30
    events:
      - http:
          path: matches
          method: get
  fetch_ml_models:
    handler: handler.fetch_ml_models
    timeout: 30
    events:
      - http:
          path: ml_models
          method: get
